# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-08 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areainfo',
            fields=[
                ('areaid', models.IntegerField(db_column='AreaId', primary_key=True, serialize=False, verbose_name='id')),
                ('areaname', models.CharField(blank=True, db_column='AreaName', max_length=50, null=True, verbose_name='区域名称')),
                ('sort', models.IntegerField(blank=True, db_column='Sort', null=True, verbose_name='排序号')),
                ('parentid', models.IntegerField(blank=True, db_column='ParentId', null=True, verbose_name='父id')),
            ],
            options={
                'verbose_name': '区域',
                'verbose_name_plural': '区域',
                'db_table': 'c_areainfo',
            },
        ),
    ]
