# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-09 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areainfo',
            old_name='areaid',
            new_name='AreaId',
        ),
        migrations.RenameField(
            model_name='areainfo',
            old_name='areaname',
            new_name='AreaName',
        ),
        migrations.RenameField(
            model_name='areainfo',
            old_name='parentid',
            new_name='ParentId',
        ),
        migrations.RenameField(
            model_name='areainfo',
            old_name='sort',
            new_name='Sort',
        ),
    ]
