# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-15 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20190409_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimageinfo',
            name='CarImageId',
            field=models.AutoField(db_column='CarImageId', primary_key=True, serialize=False, verbose_name='车辆图片id'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='CarId',
            field=models.AutoField(db_column='CarId', primary_key=True, serialize=False, verbose_name='车辆id'),
        ),
    ]
