# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-09 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeInfo',
            fields=[
                ('CodeId', models.IntegerField(db_column='CodeId', primary_key=True, serialize=False, verbose_name='验证码ID')),
                ('Mobile', models.CharField(blank=True, db_column='Mobile', max_length=15, null=True, verbose_name='电话号码')),
                ('CodeName', models.CharField(blank=True, db_column='CodeName', max_length=6, null=True, verbose_name='验证码')),
                ('IsRead', models.IntegerField(blank=True, db_column='IsRead', null=True, verbose_name='是否已读')),
                ('AddTime', models.DateTimeField(db_column='AddTime', verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '验证码信息',
                'db_table': 'c_codeinfo',
                'verbose_name': '验证码信息',
            },
        ),
        migrations.CreateModel(
            name='DriverAccountDetailsInfo',
            fields=[
                ('Status', models.IntegerField(blank=True, db_column='Status', null=True, verbose_name='状态')),
                ('AddUser', models.IntegerField(blank=True, db_column='AddUser', null=True, verbose_name='添加人员')),
                ('AddTime', models.DateTimeField(db_column='AddTime', verbose_name='添加时间')),
                ('LastEditUser', models.IntegerField(blank=True, db_column='LastEditUser', null=True, verbose_name='最后修改用户')),
                ('LastEditTime', models.DateTimeField(db_column='LastEditTime', verbose_name='最后修改时间')),
                ('DriverAccountDetailsId', models.IntegerField(db_column='DriverAccountDetailsId', primary_key=True, serialize=False, verbose_name='账户详情ID')),
                ('DriverAccountDetailsType', models.IntegerField(blank=True, db_column='DriverAccountDetailsType', null=True, verbose_name='账户详情类型')),
                ('DriverGoodsId', models.IntegerField(blank=True, db_column='DriverGoodsId', null=True, verbose_name='')),
                ('GoodsId', models.IntegerField(blank=True, db_column='GoodsId', null=True, verbose_name='货物ID')),
                ('DriverType', models.CharField(blank=True, db_column='DriverType', max_length=20, null=True, verbose_name='司机类型')),
                ('DriverAccountId', models.IntegerField(blank=True, db_column='DriverAccountId', null=True, verbose_name='司机账户ID')),
                ('OrderNum', models.CharField(blank=True, db_column='OrderNum', max_length=50, null=True, verbose_name='订单编号')),
                ('DriverId', models.IntegerField(blank=True, db_column='DriverId', null=True, verbose_name='司机ID')),
                ('ImageUrl', models.CharField(blank=True, db_column='ImageUrl', max_length=100, null=True, verbose_name='')),
                ('AccountMoney', models.FloatField(blank=True, db_column='AccountMoney', null=True, verbose_name='账户金额')),
                ('AccountContent', models.CharField(blank=True, db_column='AccountContent', max_length=50, null=True, verbose_name='账户内容')),
                ('IsCheck', models.IntegerField(blank=True, db_column='IsCheck', null=True, verbose_name='是否结账')),
            ],
            options={
                'verbose_name_plural': '司机账户详情信息',
                'db_table': 'c_driveraccountdetailsinfo',
                'verbose_name': '司机账户详情信息',
            },
        ),
        migrations.CreateModel(
            name='DriverAccountInfo',
            fields=[
                ('Status', models.IntegerField(blank=True, db_column='Status', null=True, verbose_name='状态')),
                ('AddUser', models.IntegerField(blank=True, db_column='AddUser', null=True, verbose_name='添加人员')),
                ('AddTime', models.DateTimeField(db_column='AddTime', verbose_name='添加时间')),
                ('LastEditUser', models.IntegerField(blank=True, db_column='LastEditUser', null=True, verbose_name='最后修改用户')),
                ('LastEditTime', models.DateTimeField(db_column='LastEditTime', verbose_name='最后修改时间')),
                ('DriverAccountId', models.IntegerField(db_column='DriverAccountId', primary_key=True, serialize=False, verbose_name='司机账户ID')),
                ('DriverId', models.IntegerField(blank=True, db_column='DriverId', null=True, verbose_name='司机ID')),
                ('Balance', models.FloatField(blank=True, db_column='Balance', null=True, verbose_name='余额')),
                ('Arrival', models.FloatField(blank=True, db_column='Arrival', null=True, verbose_name='到账')),
                ('NoArrival', models.FloatField(blank=True, db_column='NoArrival', null=True, verbose_name='未到账')),
            ],
            options={
                'verbose_name_plural': '司机账户信息',
                'db_table': 'c_driveraccountinfo',
                'verbose_name': '司机账户信息',
            },
        ),
        migrations.CreateModel(
            name='DriverGoodsInfo',
            fields=[
                ('Status', models.IntegerField(blank=True, db_column='Status', null=True, verbose_name='状态')),
                ('AddUser', models.IntegerField(blank=True, db_column='AddUser', null=True, verbose_name='添加人员')),
                ('AddTime', models.DateTimeField(db_column='AddTime', verbose_name='添加时间')),
                ('LastEditUser', models.IntegerField(blank=True, db_column='LastEditUser', null=True, verbose_name='最后修改用户')),
                ('LastEditTime', models.DateTimeField(db_column='LastEditTime', verbose_name='最后修改时间')),
                ('DriverGoodsId', models.IntegerField(db_column='DriverGoodsId', primary_key=True, serialize=False, verbose_name='司机货物ID')),
                ('DriverId', models.IntegerField(blank=True, db_column='DriverId', null=True, verbose_name='司机ID')),
                ('GoodsId', models.IntegerField(blank=True, db_column='GoodsId', null=True, verbose_name='货物ID')),
                ('DriverGoodsType', models.IntegerField(blank=True, db_column='DriverGoodsType', null=True, verbose_name='司机货物类别')),
                ('IsExtract', models.IntegerField(blank=True, db_column='IsExtract', null=True, verbose_name='是否提取')),
            ],
            options={
                'verbose_name_plural': '司机货物信息',
                'db_table': 'c_drivergoodsinfo',
                'verbose_name': '司机货物信息',
            },
        ),
        migrations.CreateModel(
            name='DriverInfo',
            fields=[
                ('Status', models.IntegerField(blank=True, db_column='Status', null=True, verbose_name='状态')),
                ('AddUser', models.IntegerField(blank=True, db_column='AddUser', null=True, verbose_name='添加人员')),
                ('AddTime', models.DateTimeField(db_column='AddTime', verbose_name='添加时间')),
                ('LastEditUser', models.IntegerField(blank=True, db_column='LastEditUser', null=True, verbose_name='最后修改用户')),
                ('LastEditTime', models.DateTimeField(db_column='LastEditTime', verbose_name='最后修改时间')),
                ('DriverId', models.IntegerField(db_column='DriverId', primary_key=True, serialize=False, verbose_name='司机ID')),
                ('DriverName', models.CharField(blank=True, db_column='DriverName', max_length=20, null=True, verbose_name='司机名字')),
                ('Gender', models.IntegerField(blank=True, db_column='Gender', null=True, verbose_name='性别')),
                ('DateOfBirth', models.DateField(blank=True, db_column='DateOfBirth', null=True, verbose_name='生日')),
                ('Mobile', models.CharField(blank=True, db_column='Mobile', max_length=15, null=True, verbose_name='手机')),
                ('PassWord', models.CharField(blank=True, db_column='PassWord', max_length=50, null=True, verbose_name='密码')),
                ('ImageUrl', models.CharField(blank=True, db_column='ImageUrl', max_length=100, null=True, verbose_name='身份证正面图片')),
                ('CardId', models.CharField(blank=True, db_column='CardId', max_length=18, null=True, verbose_name='身份证号码')),
                ('DriverLicenseUrl', models.CharField(blank=True, db_column='DriverLicenseUrl', max_length=100, null=True, verbose_name='驾驶证')),
                ('LicenseImageUrl', models.CharField(blank=True, db_column='LicenseImageUrl', max_length=100, null=True, verbose_name='行驶证')),
                ('NoTransitNum', models.IntegerField(blank=True, db_column='NoTransitNum', null=True, verbose_name='未运输数')),
                ('InTransitNum', models.IntegerField(blank=True, db_column='InTransitNum', null=True, verbose_name='运输中数')),
                ('YesTransitNum', models.IntegerField(blank=True, db_column='YesTransitNum', null=True, verbose_name='已运输数')),
                ('GoodsNum', models.IntegerField(blank=True, db_column='GoodsNum', null=True, verbose_name='好评数')),
                ('CenterNum', models.IntegerField(blank=True, db_column='CenterNum', null=True, verbose_name='中评数')),
                ('NegativeNum', models.IntegerField(blank=True, db_column='NegativeNum', null=True, verbose_name='差评数')),
                ('OrderTakeNum', models.IntegerField(blank=True, db_column='OrderTakeNum', null=True, verbose_name='接单次数')),
                ('IsCheck', models.IntegerField(blank=True, db_column='IsCheck', null=True, verbose_name='审核结果')),
                ('CarId', models.IntegerField(blank=True, db_column='CarId', null=True, verbose_name='车辆ID')),
                ('CarNum', models.CharField(blank=True, db_column='CarNum', max_length=10, null=True, verbose_name='车牌')),
                ('HeadImageUrl', models.CharField(blank=True, db_column='HeadImageUrl', max_length=100, null=True, verbose_name='头像图片')),
                ('CardBackImageUrl', models.CharField(blank=True, db_column='CardBackImageUrl', max_length=100, null=True, verbose_name='身份证背面背面图片')),
            ],
            options={
                'verbose_name_plural': '司机信息',
                'db_table': 'c_driverinfo',
                'verbose_name': '司机信息',
            },
        ),
        migrations.CreateModel(
            name='DriverSpecialLineInfo',
            fields=[
                ('DriverSpecialLineId', models.IntegerField(db_column='DriverSpecialLineId', primary_key=True, serialize=False, verbose_name='司机专线ID')),
                ('SendProvinceId', models.IntegerField(blank=True, db_column='SendProvinceId', null=True, verbose_name='')),
                ('SendCityId', models.IntegerField(blank=True, db_column='SendCityId', null=True, verbose_name='')),
                ('ArriveProvinceId', models.IntegerField(blank=True, db_column='ArriveProvinceId', null=True, verbose_name='')),
                ('ArriveCityId', models.IntegerField(blank=True, db_column='ArriveCityId', null=True, verbose_name='')),
            ],
            options={
                'verbose_name_plural': '司机专线信息',
                'db_table': 'c_driverspeciallineinfo',
                'verbose_name': '司机专线信息',
            },
        ),
    ]
