# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-15 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccountDetailsInfo',
            fields=[
                ('Status', models.IntegerField(blank=True, db_column='Status', null=True, verbose_name='状态')),
                ('AddUser', models.IntegerField(blank=True, db_column='AddUser', null=True, verbose_name='添加人员')),
                ('AddTime', models.DateTimeField(db_column='AddTime', verbose_name='添加时间')),
                ('LastEditUser', models.IntegerField(blank=True, db_column='LastEditUser', null=True, verbose_name='最后修改用户')),
                ('LastEditTime', models.DateTimeField(db_column='LastEditTime', verbose_name='最后修改时间')),
                ('CustomerAccountDetailsId', models.AutoField(db_column='CustomerAccountDetailsId', help_text='账户详细ID', primary_key=True, serialize=False)),
                ('CustomerAccountDetailsType', models.IntegerField(blank=True, db_column='CustomerAccountDetailsType', help_text='账户类型', null=True)),
                ('CustomerAccountId', models.IntegerField(blank=True, db_column='CustomerAccountId', help_text='顾客账户ID', null=True)),
                ('ImageUrl', models.CharField(blank=True, db_column='ImageUrl', max_length=100, null=True)),
                ('CustomerId', models.IntegerField(blank=True, db_column='CustomerId', help_text='账户信息ID', null=True)),
                ('AccountMoney', models.FloatField(blank=True, db_column='AccountMoney', help_text='账户金额', null=True)),
                ('IsCheck', models.IntegerField(blank=True, db_column='IsCheck', help_text='审核', null=True)),
                ('OrderNum', models.CharField(blank=True, db_column='OrderNum', help_text='订单数量', max_length=50, null=True)),
            ],
            options={
                'verbose_name': '顾客账户详细信息',
                'db_table': 'c_customeraccountdetailsinfo',
                'verbose_name_plural': '顾客账户详细信息',
            },
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('Status', models.IntegerField(blank=True, db_column='Status', null=True, verbose_name='状态')),
                ('AddUser', models.IntegerField(blank=True, db_column='AddUser', null=True, verbose_name='添加人员')),
                ('AddTime', models.DateTimeField(db_column='AddTime', verbose_name='添加时间')),
                ('LastEditUser', models.IntegerField(blank=True, db_column='LastEditUser', null=True, verbose_name='最后修改用户')),
                ('LastEditTime', models.DateTimeField(db_column='LastEditTime', verbose_name='最后修改时间')),
                ('CustomerId', models.AutoField(db_column='CustomerId', help_text='顾客ID', primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(blank=True, db_column='CustomerName', help_text='顾客名称', max_length=20, null=True)),
                ('Gender', models.IntegerField(blank=True, db_column='Gender', help_text='性别', null=True)),
                ('DateOfBirth', models.DateField(blank=True, db_column='DateOfBirth', help_text='生日', null=True)),
                ('Mobile', models.CharField(blank=True, db_column='Mobile', help_text='电话', max_length=15, null=True)),
                ('WeiXinId', models.CharField(blank=True, db_column='WeiXinId', help_text='微信号码', max_length=50, null=True)),
                ('WeiXin', models.CharField(blank=True, db_column='WeiXin', help_text='微信名称', max_length=50, null=True)),
                ('ImageUrl', models.CharField(blank=True, db_column='ImageUrl', help_text='头像链接', max_length=255, null=True)),
                ('PassWord', models.CharField(blank=True, db_column='PassWord', help_text='密码', max_length=50, null=True)),
                ('Point', models.IntegerField(blank=True, db_column='Point', help_text='积分', null=True)),
                ('PublishNum', models.IntegerField(blank=True, db_column='PublishNum', help_text='发布数', null=True)),
                ('TradingNum', models.IntegerField(blank=True, db_column='TradingNum', help_text='交易数', null=True)),
                ('NoTransitNum', models.IntegerField(blank=True, db_column='NoTransitNum', help_text='未运输数', null=True)),
                ('InTransitNum', models.IntegerField(blank=True, db_column='InTransitNum', help_text='运输中数', null=True)),
                ('YesTransitNum', models.IntegerField(blank=True, db_column='YesTransitNum', help_text='已运达数', null=True)),
                ('LinkCustomerId', models.IntegerField(blank=True, db_column='LinkCustomerId', help_text='推荐人ID', null=True)),
                ('IsCheck', models.IntegerField(blank=True, db_column='IsCheck', help_text='审核状态', null=True)),
            ],
            options={
                'verbose_name': '车辆信息',
                'db_table': 'c_customerinfo',
                'verbose_name_plural': '车辆信息',
            },
        ),
    ]
