# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-15 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeraccountinfo',
            options={'verbose_name': '顾客账户信息', 'verbose_name_plural': '顾客账户信息'},
        ),
    ]
