# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-16 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20190416_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccountInfo',
            fields=[
                ('Status', models.IntegerField(blank=True, db_column='Status', null=True, verbose_name='状态')),
                ('AddUser', models.IntegerField(blank=True, db_column='AddUser', null=True, verbose_name='添加人员')),
                ('AddTime', models.DateTimeField(db_column='AddTime', verbose_name='添加时间')),
                ('LastEditUser', models.IntegerField(blank=True, db_column='LastEditUser', null=True, verbose_name='最后修改用户')),
                ('LastEditTime', models.DateTimeField(db_column='LastEditTime', verbose_name='最后修改时间')),
                ('CustomerAccountId', models.AutoField(db_column='CustomerAccountId', help_text='账户ID', primary_key=True, serialize=False)),
                ('CustomerId', models.IntegerField(blank=True, db_column='CustomerId', help_text='顾客ID', null=True)),
                ('Balance', models.FloatField(blank=True, db_column='Balance', help_text='余额', null=True)),
                ('Arrival', models.FloatField(blank=True, db_column='Arrival', help_text='到账', null=True)),
                ('NoArrival', models.FloatField(blank=True, db_column='NoArrival', help_text='未到账', null=True)),
            ],
            options={
                'verbose_name_plural': '顾客账户信息',
                'db_table': 'c_customeraccountinfo',
                'verbose_name': '顾客账户信息',
            },
        ),
    ]
