# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-10 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsCommentImageInfo',
            fields=[
                ('Status', models.IntegerField(blank=True, db_column='Status', null=True, verbose_name='状态')),
                ('AddUser', models.IntegerField(blank=True, db_column='AddUser', null=True, verbose_name='添加人员')),
                ('AddTime', models.DateTimeField(db_column='AddTime', verbose_name='添加时间')),
                ('LastEditUser', models.IntegerField(blank=True, db_column='LastEditUser', null=True, verbose_name='最后修改用户')),
                ('LastEditTime', models.DateTimeField(db_column='LastEditTime', verbose_name='最后修改时间')),
                ('GoodsCommentImageId', models.AutoField(db_column='GoodsCommentImageId', primary_key=True, serialize=False, verbose_name='')),
                ('Type', models.IntegerField(blank=True, db_column='Type', null=True, verbose_name='')),
                ('GoodsId', models.IntegerField(blank=True, db_column='GoodsId', null=True, verbose_name='')),
                ('ImageUrl', models.CharField(blank=True, db_column='ImageUrl', max_length=100, null=True, verbose_name='')),
                ('IsCheck', models.IntegerField(blank=True, db_column='IsCheck', null=True, verbose_name='')),
            ],
            options={
                'verbose_name': '货单评论信息',
                'db_table': 'c_goodscommentimageinfo',
                'verbose_name_plural': '货单评论信息',
            },
        ),
        migrations.CreateModel(
            name='GoodsImageInfo',
            fields=[
                ('Status', models.IntegerField(blank=True, db_column='Status', null=True, verbose_name='状态')),
                ('AddUser', models.IntegerField(blank=True, db_column='AddUser', null=True, verbose_name='添加人员')),
                ('AddTime', models.DateTimeField(db_column='AddTime', verbose_name='添加时间')),
                ('LastEditUser', models.IntegerField(blank=True, db_column='LastEditUser', null=True, verbose_name='最后修改用户')),
                ('LastEditTime', models.DateTimeField(db_column='LastEditTime', verbose_name='最后修改时间')),
                ('GoodsImageId', models.AutoField(db_column='GoodsImageId', primary_key=True, serialize=False, verbose_name='')),
                ('GoodsId', models.IntegerField(blank=True, db_column='GoodsId', null=True, verbose_name='')),
                ('ImageUrl', models.CharField(blank=True, db_column='ImageUrl', max_length=100, null=True, verbose_name='')),
                ('IsCover', models.IntegerField(blank=True, db_column='IsCover', null=True, verbose_name='')),
                ('IsCheck', models.IntegerField(blank=True, db_column='IsCheck', null=True, verbose_name='')),
            ],
            options={
                'verbose_name': '货单图片信息',
                'db_table': 'c_goodsimageinfo',
                'verbose_name_plural': '货单图片信息',
            },
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('Status', models.IntegerField(blank=True, db_column='Status', null=True, verbose_name='状态')),
                ('AddUser', models.IntegerField(blank=True, db_column='AddUser', null=True, verbose_name='添加人员')),
                ('AddTime', models.DateTimeField(db_column='AddTime', verbose_name='添加时间')),
                ('LastEditUser', models.IntegerField(blank=True, db_column='LastEditUser', null=True, verbose_name='最后修改用户')),
                ('LastEditTime', models.DateTimeField(db_column='LastEditTime', verbose_name='最后修改时间')),
                ('GoodsId', models.AutoField(db_column='GoodsId', primary_key=True, serialize=False, verbose_name='')),
                ('GoodsNo', models.CharField(blank=True, db_column='GoodsNo', max_length=15, null=True, verbose_name='')),
                ('OutTradeNo', models.CharField(blank=True, db_column='OutTradeNo', max_length=32, null=True, verbose_name='')),
                ('GoodsType', models.IntegerField(blank=True, db_column='GoodsType', null=True, verbose_name='')),
                ('GoodsStatus', models.IntegerField(blank=True, db_column='GoodsStatus', null=True, verbose_name='')),
                ('CarId', models.IntegerField(blank=True, db_column='CarId', null=True, verbose_name='')),
                ('CarName', models.CharField(blank=True, db_column='CarName', max_length=20, null=True, verbose_name='')),
                ('CustomerId', models.IntegerField(blank=True, db_column='CustomerId', null=True, verbose_name='')),
                ('ModeOfPayment', models.CharField(blank=True, db_column='ModeOfPayment', max_length=20, null=True, verbose_name='')),
                ('GoodsFreight', models.FloatField(blank=True, db_column='GoodsFreight', null=True, verbose_name='')),
                ('CustomerPay', models.FloatField(blank=True, db_column='CustomerPay', null=True, verbose_name='')),
                ('DriverId', models.IntegerField(blank=True, db_column='DriverId', null=True, verbose_name='')),
                ('MakeToOrderDate', models.DateTimeField(db_column='MakeToOrderDate')),
                ('GoodsName', models.CharField(blank=True, db_column='GoodsName', max_length=30, null=True, verbose_name='')),
                ('LoadModeId', models.IntegerField(blank=True, db_column='LoadModeId', null=True, verbose_name='')),
                ('LoadTime', models.DateTimeField(db_column='LoadTime')),
                ('SendProvinceId', models.IntegerField(blank=True, db_column='SendProvinceId', null=True, verbose_name='')),
                ('SendCityId', models.IntegerField(blank=True, db_column='SendCityId', null=True, verbose_name='')),
                ('SendDistricId', models.IntegerField(blank=True, db_column='SendDistricId', null=True, verbose_name='')),
                ('SendAddress', models.CharField(blank=True, db_column='SendAddress', max_length=200, null=True, verbose_name='')),
                ('PublishName', models.CharField(blank=True, db_column='PublishName', max_length=20, null=True, verbose_name='')),
                ('PublishPhone', models.CharField(blank=True, db_column='PublishPhone', max_length=15, null=True, verbose_name='')),
                ('PublishDate', models.DateTimeField(db_column='PublishDate')),
                ('PublishRemark', models.CharField(blank=True, db_column='PublishRemark', max_length=50, null=True, verbose_name='')),
                ('ArriveProvinceId', models.IntegerField(blank=True, db_column='ArriveProvinceId', null=True, verbose_name='')),
                ('ArriveCityId', models.IntegerField(blank=True, db_column='ArriveCityId', null=True, verbose_name='')),
                ('ArriveDistricId', models.IntegerField(blank=True, db_column='ArriveDistricId', null=True, verbose_name='')),
                ('ArriveAddress', models.CharField(blank=True, db_column='ArriveAddress', max_length=200, null=True, verbose_name='')),
                ('UnloadingTime', models.DateTimeField(db_column='UnloadingTime')),
                ('Distance', models.FloatField(blank=True, db_column='Distance', null=True, verbose_name='')),
                ('Grabbing', models.DateTimeField(db_column='Grabbing')),
                ('Weight', models.FloatField(blank=True, db_column='Weight', null=True, verbose_name='')),
                ('Volume', models.FloatField(blank=True, db_column='Volume', null=True, verbose_name='')),
                ('KM', models.FloatField(blank=True, db_column='KM', null=True, verbose_name='')),
                ('IsCheck', models.IntegerField(blank=True, db_column='IsCheck', null=True, verbose_name='')),
                ('C_IsComment', models.IntegerField(blank=True, db_column='C_IsComment', null=True, verbose_name='')),
                ('C_CommentContent', models.CharField(blank=True, db_column='C_CommentContent', max_length=200, null=True, verbose_name='')),
                ('C_CommentScore', models.IntegerField(blank=True, db_column='C_CommentScore', null=True, verbose_name='')),
                ('D_IsComment', models.IntegerField(blank=True, db_column='D_IsComment', null=True, verbose_name='')),
                ('D_CommentContent', models.CharField(blank=True, db_column='D_CommentContent', max_length=200, null=True, verbose_name='')),
                ('D_CommentScore', models.IntegerField(blank=True, db_column='D_CommentScore', null=True, verbose_name='')),
                ('SendX', models.CharField(blank=True, db_column='SendX', max_length=30, null=True, verbose_name='')),
                ('SendY', models.CharField(blank=True, db_column='SendY', max_length=30, null=True, verbose_name='')),
                ('ArriveX', models.CharField(blank=True, db_column='ArriveX', max_length=30, null=True, verbose_name='')),
                ('ArriveY', models.CharField(blank=True, db_column='ArriveY', max_length=30, null=True, verbose_name='')),
            ],
            options={
                'verbose_name': '货单信息',
                'db_table': 'c_goodsinfo',
                'verbose_name_plural': '货单信息',
            },
        ),
    ]
