# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-15 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsimageinfo',
            name='GoodsId',
            field=models.IntegerField(blank=True, db_column='GoodsId', null=True, verbose_name='货单ID'),
        ),
        migrations.AlterField(
            model_name='goodsimageinfo',
            name='GoodsImageId',
            field=models.AutoField(db_column='GoodsImageId', primary_key=True, serialize=False, verbose_name='图片ID'),
        ),
        migrations.AlterField(
            model_name='goodsimageinfo',
            name='ImageUrl',
            field=models.CharField(blank=True, db_column='ImageUrl', max_length=100, null=True, verbose_name='图片路径'),
        ),
        migrations.AlterField(
            model_name='goodsimageinfo',
            name='IsCheck',
            field=models.IntegerField(blank=True, db_column='IsCheck', null=True, verbose_name='是否审核'),
        ),
        migrations.AlterField(
            model_name='goodsimageinfo',
            name='IsCover',
            field=models.IntegerField(blank=True, db_column='IsCover', null=True, verbose_name='是否封面'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='ArriveAddress',
            field=models.CharField(blank=True, db_column='ArriveAddress', max_length=200, null=True, verbose_name='到达地址'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='ArriveCityId',
            field=models.IntegerField(blank=True, db_column='ArriveCityId', help_text='到达地城市ID', null=True, verbose_name='到达地城市ID'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='ArriveDistricId',
            field=models.IntegerField(blank=True, db_column='ArriveDistricId', help_text='到达地区县ID', null=True, verbose_name='到达地区县ID'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='ArriveProvinceId',
            field=models.IntegerField(blank=True, db_column='ArriveProvinceId', help_text='到达地省份ID', null=True, verbose_name='到达地省份ID'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='ArriveX',
            field=models.CharField(blank=True, db_column='ArriveX', max_length=30, null=True, verbose_name='目标地坐标X'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='ArriveY',
            field=models.CharField(blank=True, db_column='ArriveY', max_length=30, null=True, verbose_name='目标地坐标Y'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='C_CommentContent',
            field=models.CharField(blank=True, db_column='C_CommentContent', max_length=200, null=True, verbose_name='客户评论内容'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='C_CommentScore',
            field=models.IntegerField(blank=True, db_column='C_CommentScore', null=True, verbose_name='客户评分'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='C_IsComment',
            field=models.IntegerField(blank=True, db_column='C_IsComment', null=True, verbose_name='客户是否允许评论'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='CarId',
            field=models.IntegerField(blank=True, db_column='CarId', null=True, verbose_name='车辆ID'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='CarName',
            field=models.CharField(blank=True, db_column='CarName', help_text='车辆类型中文名称', max_length=20, null=True, verbose_name='车辆名称'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='CustomerId',
            field=models.IntegerField(blank=True, db_column='CustomerId', null=True, verbose_name='顾客ID'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='D_CommentContent',
            field=models.CharField(blank=True, db_column='D_CommentContent', max_length=200, null=True, verbose_name='司机评论内容'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='D_CommentScore',
            field=models.IntegerField(blank=True, db_column='D_CommentScore', null=True, verbose_name='司机评分'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='D_IsComment',
            field=models.IntegerField(blank=True, db_column='D_IsComment', null=True, verbose_name='司机是否允许评论'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='Distance',
            field=models.FloatField(blank=True, db_column='Distance', null=True, verbose_name='距离'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='DriverId',
            field=models.IntegerField(blank=True, db_column='DriverId', null=True, verbose_name='司机ID'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='GoodsFreight',
            field=models.FloatField(blank=True, db_column='GoodsFreight', null=True, verbose_name='运费'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='GoodsId',
            field=models.AutoField(db_column='GoodsId', primary_key=True, serialize=False, verbose_name='货单ID'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='GoodsName',
            field=models.CharField(blank=True, db_column='GoodsName', max_length=30, null=True, verbose_name='货物名称'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='GoodsNo',
            field=models.CharField(blank=True, db_column='GoodsNo', max_length=15, null=True, verbose_name='货单号'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='GoodsStatus',
            field=models.IntegerField(blank=True, db_column='GoodsStatus', null=True, verbose_name='货单状态'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='GoodsType',
            field=models.IntegerField(blank=True, db_column='GoodsType', help_text='货单类型', null=True, verbose_name='货单类型'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='Grabbing',
            field=models.DateTimeField(db_column='Grabbing', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='IsCheck',
            field=models.IntegerField(blank=True, db_column='IsCheck', null=True, verbose_name='是否入账'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='KM',
            field=models.FloatField(blank=True, db_column='KM', null=True, verbose_name='距离'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='LoadModeId',
            field=models.IntegerField(blank=True, db_column='LoadModeId', null=True, verbose_name='装车方式ID'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='LoadTime',
            field=models.DateTimeField(db_column='LoadTime', verbose_name='装车时间'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='MakeToOrderDate',
            field=models.DateTimeField(db_column='MakeToOrderDate', verbose_name='接单时间'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='ModeOfPayment',
            field=models.CharField(blank=True, db_column='ModeOfPayment', max_length=20, null=True, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='OutTradeNo',
            field=models.CharField(blank=True, db_column='OutTradeNo', max_length=32, null=True, verbose_name='外部订单号'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='PublishDate',
            field=models.DateTimeField(db_column='PublishDate', verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='PublishName',
            field=models.CharField(blank=True, db_column='PublishName', max_length=20, null=True, verbose_name='发布姓名'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='PublishPhone',
            field=models.CharField(blank=True, db_column='PublishPhone', max_length=15, null=True, verbose_name='发布电话'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='PublishRemark',
            field=models.CharField(blank=True, db_column='PublishRemark', max_length=50, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='SendAddress',
            field=models.CharField(blank=True, db_column='SendAddress', max_length=200, null=True, verbose_name='起始地址'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='SendCityId',
            field=models.IntegerField(blank=True, db_column='SendCityId', help_text='起始地城市ID', null=True, verbose_name='起始地城市ID'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='SendDistricId',
            field=models.IntegerField(blank=True, db_column='SendDistricId', help_text='起始地区县ID', null=True, verbose_name='起始地区县ID'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='SendProvinceId',
            field=models.IntegerField(blank=True, db_column='SendProvinceId', help_text='起始地省份ID', null=True, verbose_name='起始地省份ID'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='SendX',
            field=models.CharField(blank=True, db_column='SendX', max_length=30, null=True, verbose_name='起始地坐标X'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='SendY',
            field=models.CharField(blank=True, db_column='SendY', max_length=30, null=True, verbose_name='起始地坐标Y'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='UnloadingTime',
            field=models.DateTimeField(db_column='UnloadingTime', verbose_name='卸货时间'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='Volume',
            field=models.FloatField(blank=True, db_column='Volume', null=True, verbose_name='体积'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='Weight',
            field=models.FloatField(blank=True, db_column='Weight', null=True, verbose_name='重量'),
        ),
    ]
