# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-16 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190415_1906'),
    ]

    operations = [
    ]
