# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-16 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20190416_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='KmPriceInfo',
            fields=[
                ('Status', models.IntegerField(blank=True, db_column='Status', null=True, verbose_name='状态')),
                ('AddUser', models.IntegerField(blank=True, db_column='AddUser', null=True, verbose_name='添加人员')),
                ('AddTime', models.DateTimeField(db_column='AddTime', verbose_name='添加时间')),
                ('LastEditUser', models.IntegerField(blank=True, db_column='LastEditUser', null=True, verbose_name='最后修改用户')),
                ('LastEditTime', models.DateTimeField(db_column='LastEditTime', verbose_name='最后修改时间')),
                ('KmPriceId', models.IntegerField(db_column='KmPriceId', help_text='主键ID', primary_key=True, serialize=False)),
                ('CarId', models.IntegerField(blank=True, db_column='CarId', help_text='车辆类型ID', null=True)),
                ('KmPriceType', models.IntegerField(blank=True, db_column='KmPriceType', help_text='计价方式', null=True)),
                ('StartKm', models.FloatField(blank=True, db_column='StartKm', help_text='起始公里数', null=True)),
                ('StartKmPrice', models.FloatField(blank=True, db_column='StartKmPrice', help_text='起步价格', null=True)),
                ('ExceedStartKm', models.FloatField(blank=True, db_column='ExceedStartKm', help_text='超出公里数', null=True)),
                ('ExceedStartKmPrice', models.FloatField(blank=True, db_column='ExceedStartKmPrice', help_text='超出价格', null=True)),
                ('StartVolume', models.FloatField(blank=True, db_column='StartVolume', help_text='起步体积', null=True)),
                ('StartVolumePrice', models.FloatField(blank=True, db_column='StartVolumePrice', help_text='起步体积价格', null=True)),
                ('ExceedVolume', models.FloatField(blank=True, db_column='ExceedVolume', help_text='超出体积', null=True)),
                ('ExceedVolumePrice', models.FloatField(blank=True, db_column='ExceedVolumePrice', help_text='超出体积价格', null=True)),
                ('StartWeight', models.FloatField(blank=True, db_column='StartWeight', help_text='起步重力', null=True)),
                ('StartWeightPrice', models.FloatField(blank=True, db_column='StartWeightPrice', help_text='起步重力价格', null=True)),
                ('ExceedStartWeight', models.FloatField(blank=True, db_column='ExceedStartWeight', help_text='超出体积', null=True)),
                ('ExceedStartWeightPrice', models.FloatField(blank=True, db_column='ExceedStartWeightPrice', help_text='超出体积价格', null=True)),
            ],
            options={
                'verbose_name_plural': '运费价格信息',
                'verbose_name': '运费价格信息',
                'db_table': 'm_kmpriceinfo',
            },
        ),
    ]
